version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AI_SERVICE_URL=http://ai-service:5001
    volumes:
      - "./backend:/app"
      - "/app/node_modules"
      - "./backend/dist:/app/dist"
    command: npm run start
    depends_on:
      - ai-service
    networks:
      - app-network

  ai-service:
    build: ./ai
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - "./ai:/app"
      - /app/__pycache__
    command: python app.py
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - AI_SERVICE_URL=http://ai-service:5001
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
      - "./frontend/.next:/app/.next"
      - "./frontend/public:/app/public"
    command: npm run dev
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
